MO: 2790004600
SECURITY_CODE: 52-005353
PANEL_NUM: 5 
LASER_MODE: 2  # 1: TCP, 2: RS232
LASER_IP: 10.153.227.38
LASER_PORT: 50002
LASER_SCRIPT: 20
LASER_TIMEOUT_MS: 5000
LASER_COM_PORT: COM5
LASER_BAUDRATE: 9600




