PANEL_NO: PANEL001
MO: 2790004600
SECURITY_CODE: 52-005353
PANEL_NUM: 18   
LASER_IP: 172.20.10.5                                                    
LASER_PORT: 50002
LASER_SCRIPT: "15"
LASER_TIMEOUT_MS: 3000