MO: 2790004600
OP_NUM: F9385022
PANEL_NUM: 5 
LASER_MODE: 2  # 1: TCP, 2: RS232
LASER_IP: 10.153.227.38
LASER_PORT: 50002
LASER_SCRIPT: 20
LASER_TIMEOUT_MS: 1000
LASER_COM_PORT: COM5
LASER_BAUDRATE: 9600
SFIS_COM: COM8
PLC_COM: COM3




