PANEL_NO: PANEL001
MO: 2790004585
SECURITY_CODE: 52-005353
Panel_Num: 10      # Panel Number
LASER_IP: 192.168.1.20                                                      
LASER_PORT: 50002
LASER_SCRIPT: "15"
LASER_TIMEOUT_MS: 3000